name       : lagrange
version    : 0.16.7
release    : 6
source     :
    - https://git.skyjake.fi/gemini/lagrange/releases/download/v1.16.7/lagrange-1.16.7.tar.gz : 751f595b7e913ea8246fa4031f63c15dcef1cb114e057b2062fc601875ebe745
homepage   : https://gmi.skyjake.fi/lagrange/
license    : BSD-2-Clause
component  : network.clients
summary    : A Beautiful Gemini and Gopher client
description: |
    Lagrange is a desktop GUI client for browsing Geminispace and Gopherspace. It offers modern conveniences familiar from web browsers, such as smooth scrolling, inline image viewing, multiple tabs, visual themes, Unicode fonts, bookmarks, history, gempub support, split view and page outlines.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(sdl2)
    - pkgconfig(libwebp)
    - pkgconfig(x11)
    - libunistring-devel
rundeps    :
    - mpg123
setup      : |
    %cmake_ninja -DTFDN_ENABLE_SSE41=No
build      : |
    %ninja_build
install    : |
    %ninja_install
